<?php
/**
 * Copyright © element119. All rights reserved.
 * See LICENCE.txt for licence details.
 */
declare(strict_types=1);

use Magento\Backend\Block\Template;
use Magento\Framework\Escaper;

/** @var Template $block */
/** @var Escaper $escaper */
?>
<div class="module-list-link">
    <a href="<?= $escaper->escapeUrl($block->getUrl('modules')); ?>">
        <?= $escaper->escapeHtml(__('See all module versions...')); ?>
    </a>
</div>
